// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import type { HubState } from '../../../src/lib/api'
import type { Workspace, DirEntry } from '../../../src/lib/api'

export function BrandName(): Promise<string>
export function GetHubState(): Promise<HubState>
export function ListWorkspaces(): Promise<Workspace[]>
export function OpenWorkspace(arg1: string): Promise<Workspace>
export function SwitchWorkspace(arg1: string): Promise<Workspace>
export function ListDir(arg1: string, arg2: string): Promise<DirEntry[]>
export function SelectFile(arg1: string): Promise<HubState>
export function ReadFile(arg1: string, arg2: string): Promise<string>
export function StatusMessage(): Promise<string>
export function CreateFile(arg1: string, arg2: string, arg3: string): Promise<{ path: string; absolute?: string; is_dir?: boolean; message?: string }>
export function CreateFolder(arg1: string, arg2: string, arg3: string): Promise<{ path: string; absolute?: string; is_dir?: boolean; message?: string }>
export function RenamePath(arg1: string, arg2: string, arg3: string): Promise<{ path: string; absolute?: string; is_dir?: boolean; message?: string }>
export function DeletePath(arg1: string, arg2: string): Promise<{ path: string; absolute?: string; is_dir?: boolean; message?: string }>
export function ResolvePath(arg1: string, arg2: string): Promise<{ relative: string; absolute: string; exists: boolean; is_dir: boolean }>
export function RevealInOS(arg1: string, arg2: string): Promise<{ path: string; absolute?: string; is_dir?: boolean; message?: string }>
export function RemoveWorkspace(arg1: string): Promise<void>
export function AddFolderToWorkspace(arg1: string, arg2: string): Promise<Workspace>
